language: pt-BR
tone_instructions: ""
early_access: false
enable_free_tier: true
reviews:
  profile: chill
  request_changes_workflow: true
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  auto_title_placeholder: "@coderabbitai"
  review_status: true
  poem: true
  collapse_walkthrough: true
  sequence_diagrams: true
  changed_files_summary: true
  labeling_instructions: []
  path_filters: []
  path_instructions:
    - path: "**/*.*"
      instructions: |
        Seja extremamente rigoroso na revisão de código. 
        Exija que os desenvolvedores sigam estritamente os melhores padrões de projeto. 
        Assegure que o código seja de fácil leitura, com nomes de variáveis claros, descritivos e consistentes que reflitam suas funções. 
        Garanta o uso estrito do Go com tipagem explícita, evitando o uso desnecessário de interface{}. 
        Proíba funções aninhadas desnecessariamente. 
        Assegure a modularidade e a separação de responsabilidades. 
        Limite o número de parâmetros em funções; refatore para diminuir a complexidade quando necessário. 
        Proíba o uso de fmt.Println no código. 
        Evite nomes de variáveis genéricos como temp, data, item, test, teste; prefira nomes que descrevam claramente o propósito da variável.
  abort_on_close: true
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: true
    base_branches: []
  tools:
    shellcheck:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_only: false
      level: picky
      enabled_rules: []
      disabled_rules: []
      enabled_categories: []
      disabled_categories: []
    biome:
      enabled: true
    hadolint:
      enabled: true
    swiftlint:
      enabled: true
    phpstan:
      enabled: true
      level: default
    golangci-lint:
      enabled: true
    yamllint:
      enabled: true
    gitleaks:
      enabled: true
    checkov:
      enabled: true
    detekt:
      enabled: true
    eslint:
      enabled: true
    rubocop:
      enabled: true
    buf:
      enabled: true
    regal:
      enabled: true
    actionlint:
      enabled: true
    pmd:
      enabled: true
    cppcheck:
      enabled: true
    semgrep:
      enabled: true
    circleci:
      enabled: true
    ast-grep:
      packages: []
      rule_dirs: []
      util_dirs: []
      essential_rules: true
chat:
  auto_reply: true
knowledge_base:
  opt_out: false
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    project_keys: []
  linear:
    team_keys: []
  pull_requests:
    scope: auto
