version: "3.8"
services:
  redis:
    container_name: redis
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=keyhaven
    networks:
      - keyhaven-network

  mongodb:
    image: mongo
    container_name: mongodb
    # image: bitnami/mongodb:latest
    platform: linux/arm64
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_USER=keyhaven
      - MONGODB_ROOT_PASSWORD=keyhaven
    volumes:
      - ./.docker/mongodb:/bitnami/mongodb
    networks:
      - keyhaven-network

  api:
    container_name: api
    image: my-app
    build:
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:8080"
    networks:
      - keyhaven-network
    env_file:
      - .env

  redisinsight:
    container_name: redisinsight
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"

networks:
  keyhaven-network:
    driver: bridge
