services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
